//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apuesta()
        {
            this.UsuarioApuestas = new HashSet<UsuarioApuesta>();
        }
    
        public int idApuesta { get; set; }
        public string jornada { get; set; }
        public string equipo1 { get; set; }
        public string equipo2 { get; set; }
        public short finalizado { get; set; }
        public string detalle { get; set; }
        public Nullable<int> resultado1 { get; set; }
        public Nullable<int> resultado2 { get; set; }
        public int valor { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioApuesta> UsuarioApuestas { get; set; }
    }
}
